# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM oven/bun:alpine

WORKDIR /app

# Copy package manifest and bun lock files
COPY package.json bun.lock bunbuild.toml bunfig.toml tsconfig.json ./

# Install dependencies using bun
RUN bun install

# Copy the rest of the application source code
COPY . .

# Build the project
RUN bun run build

# Expose port (if needed, but MCP usually uses stdio)

# Start the MCP server
CMD ["bun", "run", "build/index.js"]
